default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima-テックマスターのuser_id_development

test:
  <<: *default
  database: furima-テックマスターのuser_id_test

production:
  <<: *default
  database: furima-テックマスターのuser_id_production
  username: furima-テックマスターのuser_id
  password: <%= ENV["FURIMA_USER_ID_DATABASE_PASSWORD"] %>

