// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "item"
import "card"
import "category"
import "item_name"
import "star"
import "comment"
import "reply"